# -----
#  API Gateway General Settings
# -----
variable "name" {
  description = "Optional identifier to add at the end of the gateway name."
  type        = string
  default     = null
}

variable "endpoint_configuration_type" {
  description = "The endpoint configuration type (EDGE, or REGIONAL)."
  type        = string
  default     = "EDGE"
}

variable "api_template_file" {
  description = "API Gateway [OpenAPI 3](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html) template file"
}

variable "api_template_vars" {
  description = "Variables required in the OpenAPI template file"
  type        = map(any)
  default     = {}
}


# -----
#  Usage Plan Settings
# -----
variable "usage_plan_name" {
  description = "The name of your usage plan"
  type        = string
  default     = null
}

variable "quota_limit" {
  description = "The maximum number of requests that can be made in a given time period - number."
  type        = number
  default     = null
}

variable "quota_offset" {
  description = "The number of requests subtracted from the given limit in the initial time period - number"
  type        = number
  default     = null
}

variable "quota_period" {
  description = "The time period in which the limit applies. Valid values are \"DAY\", \"WEEK\" or \"MONTH\" - string"
  type        = string
  default     = null
}

variable "throttle_burst_limit" {
  description = "The API request burst limit, the maximum rate limit over a time ranging from one to a few seconds, depending upon whether the underlying token bucket is at its full capacity."
  type        = number
  default     = null
}

variable "throttle_rate_limit" {
  description = "The API request steady-state rate limit."
  type        = number
  default     = null
}


# -----
#  API Key Settings
# -----
variable "api_key_name" {
  description = "The name of the API key - string value"
  type        = string
  default     = null
}

variable "api_key_description" {
  description = "The API key description, defaults to 'Managed by Terraform' - string value"
  type        = string
  default     = null
}

variable "api_key_enabled" {
  description = "Specifies whether the API key can be used by callers - true or false"
  type        = bool
  default     = true
}

variable "api_key_value" {
  description = "The value of the API key. We highly suggest using a SOP-encrypted value. If not specified, it will be automatically generated by AWS on creation - string value"
  type        = string
  default     = null
}


# ------
#  Lambdas used by API Gateway
# ------
variable "lambda_names" {
  description = "List of lambda names that this API Gateway will need to invoke"
  type        = list(string)
  default     = []
}

# ------
#  Tags
# ------
variable "stage_name" {
  description = "A list of names the stages you wish to provision - string value"
  type        = string
}


# ------
#  Tags
# ------
variable "capsule_env" {
  description = "The environment this queue belongs to (dev, staging, production)."
  type        = string
}

variable "capsule_team" {
  description = "The team that owns this API gateway."
  type        = string
}

variable "capsule_service" {
  description = "The service that owns this API gateway."
  type        = string
}

variable "vanta_owner" {
  description = "Vanta specific tag to identify resource owner - string"
  type        = string
}

variable "vanta_description" {
  description = "Vanta specific tag to specify the purpose of resource - string value"
  type        = string
}

variable "vanta_user_data" {
  description = "Vanta specific tag to specify if the resource will contain user data - true or false"
  type        = bool
}

variable "vanta_user_data_stored" {
  description = "Vanta specific tag to specify the type of data the resource transacts/stores - string value"
  type        = string
}

variable "vanta_contains_ephi" {
  description = "Vanta specific tag to specify if the resource contains PHI - true or false"
  type        = bool
}
