name: "Tag and Release terraform module"
on:
    push:
      branches:
        - main
        - master
  
permissions: {}
  
jobs:
  example-job:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      # - name: git
      #   run: |
      #     # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
      #     git --version
      #     git config user.name "Prabesh Thapa"
      #     git config user.email "sthapaprabesh2020@gmail.com"
      #     git remote set-url --push origin https://your_username:$GITHUB_TOKEN@github.com/your/repo
      - name: Make the script files executable
        run: chmod +x scripts/tag-n-release.sh
      - name: Run the scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/tag-n-release.sh
      # - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ISSUE: ${{ github.event.issue.html_url }}
