name: "Tag and Release terraform module"
on:
    push:
      branches:
        - main
        - master
  
permissions: {}
  
jobs:
  example-job:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Make the script files executable
        run: chmod +x scripts/tag-n-release.sh
      - name: Run the scripts
        run: bash scripts/tag-n-release.sh
